# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 324)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 331, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.buttonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoad.setGeometry(QtCore.QRect(370, 20, 151, 41))
        self.buttonLoad.setObjectName("buttonLoad")
        self.buttonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGenerate.setGeometry(QtCore.QRect(370, 80, 151, 41))
        self.buttonGenerate.setObjectName("buttonGenerate")
        self.buttonSort = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSort.setGeometry(QtCore.QRect(370, 140, 151, 61))
        self.buttonSort.setObjectName("buttonSort")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 140, 241, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 221, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(20, 200, 211, 22))
        self.spinBox.setMinimum(1000)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setObjectName("spinBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 230, 106, 21))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 261, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.textBrowser_Time = QtWidgets.QTextBrowser(self.formLayoutWidget_2)
        self.textBrowser_Time.setObjectName("textBrowser_Time")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowser_Time)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonLoad.setText(_translate("MainWindow", "Загрузить массив из файла"))
        self.buttonGenerate.setText(_translate("MainWindow", "Сгенерировать массив"))
        self.buttonSort.setText(_translate("MainWindow", "Отсортировать"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Пузырьковая"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Быстрая"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Выбором"))
        self.label.setText(_translate("MainWindow", "Тип сортировки:"))
        self.label_2.setText(_translate("MainWindow", "Число элементов для генерации массива:"))
        self.label_3.setText(_translate("MainWindow", "Время сортировки:l"))
